name: Günlük Altın Kur Bot

on:
  schedule:
    # Her gün saat 06:00 UTC (Türkiye saati ile 09:00)
    - cron: '0 6 * * *'
  workflow_dispatch: # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Playwright kur
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          python -m playwright install chromium

      - name: Telegram Bot Çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python kur_bot.py
